hf_model: "FacebookAI/xlm-roberta-large"
experiment_name: "baseline_v1_0"
experiment_tag: ""
eval_strategy: "steps"
n_steps: 4000
num_train_epochs: 200
batch_size: 1
eval_batch_size: 1
eval_beam_size": 800
gradient_accumulation_steps: 1
gradient_checkpointing: False
learning_rate: 2e-05
validation_freq: 20
checkpoint: null
logging_step: 10
warmup_steps: 100
logging_dir: "./logs/training"
eval_steps: 20
save_step: 20
bf16: false
fp16: true
use_8adam: false
optim: "adamw_hf"
label_smoothing_factor: 0.0
log_wandb: false
env: "test"
saved_model_dir: "../saved_model/test"
n_folds: 5
use_lora: false
tags_to_merge:
  - "fact"
  - "report"
  - "description"
tags_to_remove:
  - "threat"
  - "insult"
do_soft: true
use_merged: true
split_by_topic: true
