hf_model: "FacebookAI/xlm-roberta-large"
dataset_path: "./data/dataset/viclaim.csv"
experiment_name: "baseline_v1_0"
experiment_tag: ""
eval_strategy: "steps"
num_training_steps: 4000
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
gradient_checkpointing: False
learning_rate: 2e-05
logging_steps: 10
warmup_steps: 100
logging_dir: "./logs/training"
eval_steps: 20
save_steps: 20
bf16: false
fp16: true
optim: "adamw_torch"
label_smoothing_factor: 0.0
saved_model_dir: "./data/saved_model/"
n_folds: 5
test_size: 0.01
use_lora: false
split_by_topic: true
save_total_limit: 2
use_full_context: true
topic_list:
  - "US Elections 2024"
  - "War in Ukraine"
  - "Migration"
  - "Societal issues in the US."
  - "European Union"
  - "League of Legends"
