hf_model: "meta-llama/Llama-3.2-3B"
experiment_name: "baseline_v1_0"
experiment_tag: ""
eval_strategy: "steps"
num_training_steps: 500
per_device_train_batch_size: 1
# per_device_train_batch_size: 64
per_device_eval_batch_size: 1
# per_device_eval_batch_size: 64
gradient_accumulation_steps: 8
gradient_checkpointing: False
learning_rate: 5e-04
logging_steps: 10
warmup_steps: 100
logging_dir: "../../training_outputs/logs/"
wandb_dir: "../../training_outputs/wandb/"
eval_steps: 20
save_steps: 20
bf16: false
fp16: true
optim: "adamw_torch"
label_smoothing_factor: 0.0
saved_model_dir: "../../training_outputs/saved_model/"
n_folds: 5
test_size: 0.15
use_lora: true
split_by_topic: true
save_total_limit: 2
use_full_context: true
topic_list:
  - "US Elections 2024"
  - "War in Ukraine"
  - "Migration"
  - "Societal issues in the US."
  - "European Union"
  - "League of Legends"
